### ISSUE TITLE
Building a Helm Chart for dask

### ISSUE THREAD

**Issue by SaMnCo** [martindurant/dask-kubernetes#9]
Hi Martin, 

I am doing some work in the Kubernetes space around ML / DL, mostly on the infrastructure side to make it easy to onboard clustering. One of the things I have worked on is a Helm chart for Tensorflow (write up [here](https://medium.com/intuitionmachine/kubernetes-gpus-tensorflow-8696232862ca))

Someone told me that Anaconda would make a lot of sense, so I started looking into ways to run it on K8s, and your repo is the most advanced setup I can find. However, I try to stick to Helm packages in general, and you don't have that. 

Are you accepting PRs, and is this something you would value? 
If not, do you mind if I borrow your structure to start a chart? Any license you'd like to apply? 

Many thanks! I am also available on Twitter to discuss @SaMnCo_23.

**Comment by martindurant** [comment]
This is certainly something that we aim to do. In fact, @danielfrg had a helm version of dask-kubernetes' predecessor. I would be more than happy to see the kubernetes template parameters in the yaml files named as variables and moved into a separate parameter input file.

Whether this is a PR or a fork is your choice, we would be happy to see either. The advantage of a PR is that we can incorporate your work into this repo, but it may be a little more complex. Adding a license should be raised as an issue here - BSD is typical for dask-related projects. It will be fully open source.

**Comment by SaMnCo** [comment]
OK cool thanks. I'll get started on this, it doesn't seem to be too complicated to get to something similar to your current setup. 

Quick questions (I am not familiar with dask at all, so these are maybe very stupid...)

* Can/should you leverage GPUs in this context, even optionally? ([this](http://distributed.readthedocs.io/en/latest/resources.html) looks very "runtime oriented"
* Do you need to handle storage for datasets? I didn't find any reference to data stores in your files yet. 

Thanks! 
Best,
Sam

**Comment by martindurant** [comment]
- there has been no thought to GPUs, but I guess the machine types could be whatever you like. The current pattern doesn't really lend itself to a mixture of GPU and non-GPU machines. (I would like in the long run to have some "cluster management" functionality in the scheduler container, rather than controlling everything from the local machine, so there could be "add GPU machine"  options there)
- I do have a [library](https://github.com/martindurant/gcsfs/) for GCS interaction, which works with dask, but there is no especial need for data to live there. If you mean persistent mountable storage, no, I have not thought about that at all.

**Comment by martindurant** [comment]
Fixed in #25
